# vim:ff=unix ts=2 sw=2 ai expandtab
version: "3.7"
services:
  jql:
    image: jql
    init: true
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - "./jql/:/code/jql/:ro"
      - "mypycache:/tmp/mypycache"
volumes:
  mypycache:
