FROM python:3.8-slim

MAINTAINER Aaron Barnes <aaron@io.nz>

RUN adduser --system --no-create-home --disabled-login jql
ENV PYTHONUNBUFFERED=1

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y python3-pip python3-dev

ENV PYTHONPATH="/code/:${PYTHONPATH}"

CMD ["pytest", "-p", "no:cacheprovider"]

RUN mkdir /code
WORKDIR /code

ADD requirements.txt /tmp/
ADD requirements-test.txt /tmp/

RUN pip install --upgrade pip
RUN pip install -r /tmp/requirements-test.txt

COPY .flake8 /code/
COPY *.py /code/

USER jql

RUN flake8
