# vim:ff=unix ts=2 sw=2 ai expandtab
version: "3.7"
services:
  db:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/test
    volumes:
      - "${PWD}/data:/data"
      - "${PWD}/logs:/logs"
    ports:
      - "7474:7474"
      - "7687:7687"
