FROM python:3.10-slim

MAINTAINER Aaron Barnes <aaron@io.nz>

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y python3-pip python3-dev

ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH="/code/:/code/vendor/:${PYTHONPATH}"
ENV MYPYPATH="/code/:/code/vendor/"
ENV DEBUG=1

RUN mkdir /code
WORKDIR /code

ADD requirements-test.txt /tmp/

RUN pip install --upgrade pip wheel
RUN pip install -r /tmp/requirements-test.txt

CMD ["/code/test.sh"]

COPY vendor/ /code/vendor
COPY setup.cfg /code/
COPY setup.py /code/
COPY test.sh /code/
COPY tests/ /code/tests
COPY jql/ /code/jql
