FROM python:3.10-slim

MAINTAINER Aaron Barnes <aaron@io.nz>

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y sqlite3

ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH="/code/:/code/vendor/:${PYTHONPATH}"

RUN mkdir /code
WORKDIR /code

CMD ["python", "-m", "jql.repl", "/data/repl.jdb"]

COPY vendor/ /code/vendor
COPY jql/ /code/jql
